version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  assignees:
  - fabianfreyer
  ignore:
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: handlebars
    versions:
    - 3.5.2
    - 3.5.3
  - dependency-name: actix-service
    versions:
    - 1.0.5
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  assignees:
  - fabianfreyer
  ignore:
  - dependency-name: xterm
    versions:
    - 4.10.0
    - 4.9.0
